	tilepal 0, GRAY, RED, BROWN, BROWN, BROWN, BROWN, RED, BROWN
	tilepal 0, GREEN, GREEN, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GRAY, GREEN, BROWN, RED, GREEN, RED, BROWN
	tilepal 0, WATER, WATER, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, YELLOW
	tilepal 0, BROWN, WATER, WATER, WATER, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, YELLOW
	tilepal 0, WATER, WATER, WATER, WATER, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, WATER, WATER, RED, RED, ROOF, ROOF
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, BROWN, BROWN, WATER, WATER, RED, RED, BROWN, BROWN
	tilepal 0, GREEN, GREEN, BROWN, BROWN, GRAY, GRAY
