	tilepal 0, WATER, BROWN, BROWN, ROOF, GRAY, GRAY, ROOF, BROWN
	tilepal 0, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GRAY, WATER, GRAY, BROWN, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN, BROWN
	tilepal 0, WATER, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, WATER, WATER, BROWN, BROWN, ROOF, ROOF
	tilepal 0, GRAY, ROOF, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, ROOF, ROOF, WATER, WATER, BROWN, WATER, ROOF, ROOF
	tilepal 0, ROOF, ROOF, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, WATER, BROWN, GRAY, ROOF, WATER
	tilepal 0, GRAY, ROOF, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN

rept 16
	db $ff
endr

	tilepal 1, WATER, TEXT
