	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TEXT
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TEXT, WATER
	tilepal 0, WATER, WATER, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, TEXT
	tilepal 1, WATER, WATER, WATER, WATER, WATER, GREEN, GREEN, GREEN
	tilepal 1, GREEN